### ISSUE TITLE
Unexpected input 'token', valid inputs are ['commits']

### ISSUE THREAD

**Issue by jaymzh** [tim-actions/dco#1]
When I use the suggested YAML to configure this I get:

```
Unexpected input 'token', valid inputs are ['commits']
```

If I replace:
```yaml
with:
  token: ${{ secrets.GITHUB_TOKEN }}
```

with instead:
```yaml
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Then I get:

```
Unexpected end of JSON input
```

**Comment by Tim-Zhang** [comment]
Sorry for the late response. Can you post the full yaml here please?

**Comment by jaymzh** [comment]
Sure:

```
name: DCO Check
on: [pull_request]

jobs:
  dco_check_job:
    runs-on: ubuntu-latest
    name: DCO Check
    steps:
    - name: DCO Check
      uses: tim-actions/dco@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
```

Or see my PR to add it to my repo here:
https://github.com/jaymzh/sugarjar/pull/20/files
